### ISSUE TITLE
Merge refactoring from kimmel?

### ISSUE THREAD

**Issue by joshdoe** [apt-mirror/apt-mirror#1]
Of all the forks I've found, @kimmel has the most extensive changes, primarily in the form of refactoring, cleanup, and conformance to perlcritic:
https://github.com/kimmel/apt-mirror-fork

I've taken a quick look, but not long enough to know if the changes should be merged here.

**Comment by Raboo** [comment]
Why don't you close this issue? The kimmel fork hasn't been committed to in 6 years.

**Comment by bdrung** [comment]
Okay. Closing this ticket. Please open a pull request in case you rebase your changes on top of the current master branch.

PS: When I have too much time, I will rewrite apt-mirror in Python, Go, or Rust (including a test suite to improve maintainability).
