### ISSUE TITLE
Unlink files instead of clobbering existing ones

### ISSUE THREAD

**Issue by dr4Ke** [apt-mirror/apt-mirror#11]
We use apt-mirror for a local mirror. We want to keep some history for our mirrors, using hardlinks between two "snapshots".

The default behavior of wget is to clobber existing files if they changed. This is not something good for our setup since we want to be sure that NO file will change in previous snapshots.

We would like to use the wget option `--unlink` in apt-mirror. I'm working on a patch to enable a new variable for this.

**Comment by bdrung** [comment]
Merge proposal #14 was merged and the fix was part of apt-mirror 0.5.0.
