### ISSUE TITLE
Support for xz translations missing

### ISSUE THREAD

**Issue by pboguslawski** [apt-mirror/apt-mirror#125]
Hi,

There is no xz support in

https://github.com/apt-mirror/apt-mirror/blob/e664486a5d8947c2579e16dd793d762ea3de4202/apt-mirror#L523

which is required for compatibility with Debian 10 repos like

http://security-cdn.debian.org/dists/buster/updates/main/i18n/

Fix that works for us:

```
-                    if ( $filename =~ m{^$component/i18n/Translation-[^./]*\.bz2$} )
+                    if ( $filename =~ m{^$component/i18n/Translation-[^./]*\.(bz2|xz)$} )

```
Regards,
Pawel

**Comment by mire3212** [comment]
This also worked for me while trying to mirror Buster repos. Thanks!

**Comment by Hellnino18** [comment]
It works for me too for Buster ! Thanks @pboguslawski

**Comment by exrat** [comment]
It's ok for buster :) Thanks @pboguslawski
