### ISSUE TITLE
bz2 or xz or gz (buster-backports i18n xz)

### ISSUE THREAD

**Issue by nnfe** [apt-mirror/apt-mirror#130]
https://github.com/apt-mirror/apt-mirror/blob/7d521b168ab34fd38fd38bbb26acad1f43e262a7/apt-mirror#L523
                    if ( $filename =~ m{^$component/i18n/Translation-[^./]*\.(bz2||xz||gz)$} )

**Comment by blizzardster** [comment]
I used a stupid way

mkdir /home/www/mirror/mirrors.tuna.tsinghua.edu.cn/debian/dists/buster-backports/main/i18n/ && cd /home/www/mirror/mirrors.tuna.tsinghua.edu.cn/debian/dists/buster-backports/main/i18n/ && wget https://mirrors.tuna.tsinghua.edu.cn/debian/dists/buster-backports/main/i18n/Translation-en.xz

mkdir /home/www/mirror/mirrors.tuna.tsinghua.edu.cn/debian/dists/buster-backports/contrib/i18n/ && cd /home/www/mirror/mirrors.tuna.tsinghua.edu.cn/debian/dists/buster-backports/contrib/i18n/ && wget https://mirrors.tuna.tsinghua.edu.cn/debian/dists/buster-backports/contrib/i18n/Translation-en.xz

mkdir /home/www/mirror/mirrors.tuna.tsinghua.edu.cn/debian/dists/buster-backports/non-free/i18n/ && cd /home/www/mirror/mirrors.tuna.tsinghua.edu.cn/debian/dists/buster-backports/non-free/i18n/ && wget https://mirrors.tuna.tsinghua.edu.cn/debian/dists/buster-backports/non-free/i18n/Translation-en.xz

mkdir /home/www/mirror/mirrors.tuna.tsinghua.edu.cn/debian-security/dists/buster/updates/main/i18n/ && cd /home/www/mirror/mirrors.tuna.tsinghua.edu.cn/debian-security/dists/buster/updates/main/i18n/ && wget https://mirrors.tuna.tsinghua.edu.cn/debian-security/dists/buster/updates/main/i18n/Translation-en.xz

mkdir /home/www/mirror/mirrors.tuna.tsinghua.edu.cn/debian-security/dists/buster/updates/non-free/i18n/ && cd /home/www/mirror/mirrors.tuna.tsinghua.edu.cn/debian-security/dists/buster/updates/non-free/i18n/ && wget https://mirrors.tuna.tsinghua.edu.cn/debian-security/dists/buster/updates/non-free/i18n/Translation-en.xz
