### ISSUE TITLE
Source directory and by-hash directory missing in apt-mirror usoing Ubuntu Server 18.04

### ISSUE THREAD

**Issue by amarnath-jena** [apt-mirror/apt-mirror#134]
Source directory and by-hash directory missing in apt-mirror . I have attached my mirror list . every day whenever i run apt update . it gives me a error Hash sum mismatch. I have solved it by creating manual directories of Source directory and by-hash directory also added the required files  but still it gives hash sum mismatched on another day. Kindly help me out . I am new to apt-mirror server.
[mirror.txt](https://github.com/apt-mirror/apt-mirror/files/4253709/mirror.txt)

**Comment by flavienbwk** [comment]
Enjoy an up-to-date repo ;) 
https://github.com/flavienbwk/apt-mirror-docker
