### ISSUE TITLE
limit-rate could be made more effective

### ISSUE THREAD

**Issue by gregewing** [apt-mirror/apt-mirror#140]
Using apt-mirror and setting limit-rate (for this to be passed to wget) seems to do little to set the actual bandwidth used.  To limit to about 10Mbps plus/minus 50% i needed to set a limit-rate to 20k in mirror.list.   I accounted for the fact that limit-rate is applied to each download thread and therefore is cumulative across, say, 20 threads up to 20x the rate limit set in mirrors.list.  

I used nload to monitor the network utilisation while testing.

The man page for wget says that its not a particularly good way of rate limiting, especially for small file transfers.  So I wanted to look for an alternative.

I run apt-mirror in a docker container (flomine/apt-mirror:latest) and I'm getting much better bandwidth limiting control if I apply a limit to the veht adapter that relates to the docker image using the 'tc' command as folllows:

run on the host:
tc qdisc add dev vethffbe888 root tbf rate 10mbit burst 1mbit latency 1ms

The specific name of vethblahblah changes each time the container is restarted/redeployed, so not a perfect solution, but i'm sure there is a way to pass the veth ID from within the running container to the host, where it may be cross-referenced with the list of veth adapters on the host and use that in the 'tc' command.  I could just user the docker0 adapter, but then all docker containers would fall under the limit, and that's not what I want.

I could achieve a similar result by installing wondershaper (on the host) as a front-end to the 'tc' command, but this isn't technically necessary I don't think.

running the tc command (or wondershper) on the docker container has no effect - I was not able to figure out why.

I appreciate that the use of tc requires iproute2 to be installed, and is relevant when bandwidth limiting network cards, not specific application so not applicable to situations where apt-mirror is run as an app without a virtualisation/containerisation layer, but I get rock solid bandwidth limiting when I use this method.

So, if anyone is interested, there's a potential here to improve the way bandwidth limiting is done, perhaps only for containerised instances of apt-mirror.  But if anyone has appetite to make apt-mirror run through a virtual ethernet adapter when running directly on the tin, then the 'tc' bandwidth control method would definitely be more effective than passing limit-rate to wget.

**Comment by def0to** [comment]
We opt for wondershaper just because of the limitation on wget.Of course, we are running it on a server and not docker.
