### ISSUE TITLE
Apt-mirror for amd64 did not include focal/main/dep11 and focal/main/cnf/Commands-amd64

### ISSUE THREAD

**Issue by satishdotpatel** [apt-mirror/apt-mirror#145]
Fresh install Ubuntu 20.04.1 and install apt-mirror using apt-get install apt-mirror and found its not syncing cnf directory. can we add that directory in script which i did by hand in perl script but it would be great to come with package.

**Comment by wishfay** [comment]
i also have the same problem in Ubuntu 20.04 LTS as below, how can i solve this problem?
`
E: Failed to fetch http://localhost/ubuntu/dists/focal/main/cnf/Commands-amd64  404  Not Found [IP: 127.0.0.1 80]
E: Failed to fetch http://localhost/ubuntu/dists/focal-updates/main/cnf/Commands-amd64  404  Not Found [IP: 127.0.0.1 80]
E: Failed to fetch http://localhost/ubuntu/dists/focal-backports/main/cnf/Commands-amd64  404  Not Found [IP: 127.0.0.1 80]
E: Failed to fetch http://localhost/ubuntu/dists/focal-security/main/cnf/Commands-amd64  404  Not Found [IP: 127.0.0.1 80]
E: Failed to fetch http://localhost/ubuntu/dists/focal-proposed/main/cnf/Commands-amd64  404  Not Found [IP: 127.0.0.1 80]
`

**Comment by johncsuti** [comment]
> 
> 
> i also have the same problem in Ubuntu 20.04 LTS as below, how can i solve this problem?
> `E: Failed to fetch http://localhost/ubuntu/dists/focal/main/cnf/Commands-amd64 404 Not Found [IP: 127.0.0.1 80] E: Failed to fetch http://localhost/ubuntu/dists/focal-updates/main/cnf/Commands-amd64 404 Not Found [IP: 127.0.0.1 80] E: Failed to fetch http://localhost/ubuntu/dists/focal-backports/main/cnf/Commands-amd64 404 Not Found [IP: 127.0.0.1 80] E: Failed to fetch http://localhost/ubuntu/dists/focal-security/main/cnf/Commands-amd64 404 Not Found [IP: 127.0.0.1 80] E: Failed to fetch http://localhost/ubuntu/dists/focal-proposed/main/cnf/Commands-amd64 404 Not Found [IP: 127.0.0.1 80]`
> 
> -----------problem solved at 20210130----------------------
> write a `cnf.sh` to download all the cnf files, then copy to `mirror-data`.
> this works for me,here is the script.
> cnf.sh:
> `
> #!/bin/bash
> 
> for p in "${1:-focal}"{,-{security,updates,proposed,backports}}/{main,restricted,universe,multiverse}; do
> >&2 echo "${p}"
> wget -q -c -r -np -R "index.html*" "[http://mirrors.tuna.tsinghua.edu.cn/ubuntu/dists/${p}/cnf/Commands-amd64.xz](http://mirrors.tuna.tsinghua.edu.cn/ubuntu/dists/$%7Bp%7D/cnf/Commands-amd64.xz)"
> wget -q -c -r -np -R "index.html*" "[http://mirrors.tuna.tsinghua.edu.cn/ubuntu/dists/${p}/cnf/Commands-i386.xz](http://mirrors.tuna.tsinghua.edu.cn/ubuntu/dists/$%7Bp%7D/cnf/Commands-i386.xz)"
> done
> `

Do  you have one for more then just focal or is focal the only distro affected?

**Comment by Immortalt** [comment]
> Fresh install Ubuntu 20.04.1 and install apt-mirror using apt-get install apt-mirror and found its not syncing cnf directory. can we add that directory in script which i did by hand in perl script but it would be great to come with package.

How to modify the perl script to solve this problem? I hope to download automatically, not like @wishfay 's script that I need to copy by hand.

**Comment by bytefish163** [comment]
Add a statement after line 451：
``` perl
foreach (@config_binaries)
{
    my ( $arch, $uri, $distribution, @components ) = @{$_};

    if (@components)
    {
        $url = $uri . "/dists/" . $distribution . "/";

        add_url_to_download( $url . "InRelease" );
        add_url_to_download( $url . "Release" );
        add_url_to_download( $url . "Release.gpg" );
        if ( get_variable("_contents") )
        {
            add_url_to_download( $url . "Contents-" . $arch . ".gz" );
            add_url_to_download( $url . "Contents-" . $arch . ".bz2" );
            add_url_to_download( $url . "Contents-" . $arch . ".xz" );
        }
        foreach (@components)
        {
            if ( get_variable("_contents") )
            {
                add_url_to_download( $url . $_ . "/Contents-" . $arch . ".gz" );
                add_url_to_download( $url . $_ . "/Contents-" . $arch . ".bz2" );
                add_url_to_download( $url . $_ . "/Contents-" . $arch . ".xz" );
            }
            add_url_to_download( $url . $_ . "/binary-" . $arch . "/Release" );
            add_url_to_download( $url . $_ . "/binary-" . $arch . "/Packages.gz" );
            add_url_to_download( $url . $_ . "/binary-" . $arch . "/Packages.bz2" );
            add_url_to_download( $url . $_ . "/binary-" . $arch . "/Packages.xz" );
            add_url_to_download( $url . $_ . "/i18n/Index" );
############   Add a statement after line 451 :   ############
            add_url_to_download( $url . $_ . "/cnf/Commands-" . $arch . ".xz" );  
        }
    }
    else
    {
        add_url_to_download( $uri . "/$distribution/Release" );
        add_url_to_download( $uri . "/$distribution/Release.gpg" );
        add_url_to_download( $uri . "/$distribution/Packages.gz" );
        add_url_to_download( $uri . "/$distribution/Packages.bz2" );
        add_url_to_download( $uri . "/$distribution/Packages.xz" );
    }
}
```

> 
> 
> > Fresh install Ubuntu 20.04.1 and install apt-mirror using apt-get install apt-mirror and found its not syncing cnf directory. can we add that directory in script which i did by hand in perl script but it would be great to come with package.
> 
> How to modify the perl script to solve this problem? I hope to download automatically, not like @wishfay 's script that I need to copy by hand.

**Comment by Stifler6996** [comment]
Im maintaining a working version of apt-mirror here.

https://github.com/Stifler6996/apt-mirror

**Comment by bytefish163** [comment]
Good job !

**Comment by pcpcoreyster** [comment]
I downloaded the latest to make sure my apt-mirror server was running this version (I had updated in Feb 21, 2021).

I ran the update and the only item not working:
Failed to fetch http://aptmirror.mynetwork.io/ubuntu/dists/focal-backports/multiverse/cnf/Commands-amd64  404  Not Found [IP: x.x.x.x 80]

Here is the detail on my machine (/etc/os-release):

> NAME="Ubuntu"
> VERSION="20.04.2 LTS (Focal Fossa)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 20.04.2 LTS"
> VERSION_ID="20.04"
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> VERSION_CODENAME=focal
> UBUNTU_CODENAME=focal

**Comment by steamboatid** [comment]
> Im maintaining a working version of apt-mirror here.
> 
> https://github.com/Stifler6996/apt-mirror

please check my new PR #150 
the cnf is optional, but can be set it via config file
