### ISSUE TITLE
304 Not Modified issue

### ISSUE THREAD

**Issue by BinkyNingy2** [apt-mirror/apt-mirror#147]
I run apt-mirror, after the "Processing indexes:..." message, it states XXX bytes will be downloaded, but nothing gets downloaded.  Reviewing the log files, wget is receiving 304 Not Modified responses.  This is a problem when determining if the local repository is up to date or not.  

I modified apt-mirror and removed the "-N" from the wget command line, and re-ran, which forced the files in question to be downloaded.  I then restored apt-mirror, and it properly reports "0 bytes will be downloaded".

Please add a command-line option to apt-mirror to force wget to download, by removing "-N" from the wget command line.  

I don't think the option should be in the configuration file, because then people will forget to remove it and re-download the pan-galactic multiverse, exceeding the local information density limit and causing spontaneous generation of black-holes.  Or, at least, very dark brown holes.  Oh, that's a nasty image, right there. sorry.

**Comment by steamboatid** [comment]
i did that at PR #150 

please check it
