### ISSUE TITLE
New apt-mirror PPA

### ISSUE THREAD

**Issue by likema** [apt-mirror/apt-mirror#148]
Hi all,

I have made a new apt-mirror PPA https://launchpad.net/~likemartinma/+archive/ubuntu/apt-mirror merge or fix the following issue:

* PR #103
* PR #120
* PR #127

It is just for Ubuntu 20.04, but I guess it should also work on other Debian/Ubuntu distributions.

**Comment by mcrrx** [comment]
测试过，的确解决了上面三个问题，谢谢。

**Comment by likema** [comment]
我司一直在使用，基本正常。

**Comment by mcrrx** [comment]
> 我司一直在使用，基本正常。

您好，我想问下可以配置多个mirror.list文件吗？我想一个做debian一个做ubuntu，目前我是需要一个完成了，然后重命名另一个去执行。

**Comment by likema** [comment]
> 您好，我想问下可以配置多个mirror.list文件吗？我想一个做debian一个做ubuntu，目前我是需要一个完成了，然后重命名另一个去执行。

分别执行两次，或者把两个 mirror.list 拼接为一个？

**Comment by mcrrx** [comment]
> > 您好，我想问下可以配置多个mirror.list文件吗？我想一个做debian一个做ubuntu，目前我是需要一个完成了，然后重命名另一个去执行。
> 
> 分别执行两次，或者把两个 mirror.list 拼接为一个？

我本来是分开两次执行的，现在合成一个了，然后做个软连接就好了。谢谢啦
