### ISSUE TITLE
New apt-mirror in Python 3

### ISSUE THREAD

**Issue by xuancong84** [apt-mirror/apt-mirror#149]
I have created a Python3-version of apt-mirror (https://github.com/xuancong84/linux-home/blob/master/bin/apt-mirror.py )
It is better and more robust than apt-mirror:
- it does not require creating a new user and running sudo, any normal user can run it
- it does not require any special config file, you can specify a particular sources.list files or by default it uses your current system's `/etc/apt/sources.list` and `/etc/apt/sources.list.d/*.list`
- it contains an option `--delete-old` or `-D`, which allows you to delete outdated files so as to keep your offline mirror small in size
- it supports many kinds of Linux mirror repositories, including https://dl.winehq.org/ (hosted using non-standard Apache file listing, so that `wget --recursive` does not work), http://dl.google.com/linux/chrome/deb/ (it has disabled directory listing, so you cannot even browse directory content), and even https://developer.download.nvidia.com/compute/cuda/repos/debian10/x86_64/ (which uses absolute path for `suite`), etc.
- it supports checksum verification before or/and after downloading, for index files and for package files respectively
- after cloning all the repositories, it will generate a sources.list in the output root directory, you can readily use it on your local machine or use it on your intranet by substituting all `file:///` by your intranet Web URL prefix

You can simply add this one file into your repo directly and upon installation, just install into /usr/bin/ folder.

**Comment by windtail** [comment]
why not create a project for apt-mirror-python instead of linux-home

**Comment by xuancong84** [comment]
> why not create a project for apt-mirror-python instead of linux-home

I want to leave the name apt-mirror to official tools repository, linux-home is for my personal utility repository.
I may create a separate branch on apt-mirror to include my apt-mirror.py .

**Comment by acc2021** [comment]
@xuancong84 
Does the script support downloading packages only for certain architectures?
The original apt-mirror does. But it seems when giving the python version a sources.list with "deb-arm64 http://mirror..."
or some other arch it seems to ignore the architecture and just downloads everything

**Comment by xuancong84** [comment]
> @xuancong84 Does the script support downloading packages only for certain architectures? The original apt-mirror does. But it seems when giving the python version a sources.list with "deb-arm64 http://mirror..." or some other arch it seems to ignore the architecture and just downloads everything

Yes. If you put `[arch=amd64,i386]` then it will only download amd64 and i386. However, if you don't put anything, it will download all architectures.

**Comment by angeletakis** [comment]
You are using an undeclared variable `delete_old` on line [297](https://github.com/xuancong84/linux-home/blob/5cb727fc7e989d0fe60bac75fce405f24c74d24b/bin/apt-mirror.py#L297)

**Comment by xuancong84** [comment]
Dear @angeletakis , there is no good or bad practice, I also do not want to do this way. Unfortunately, Python does not support the functionality I wanted.
