### ISSUE TITLE
Unable to setup apt-mirror local reposiraty ubuntu 20.04

### ISSUE THREAD

**Issue by sowmian** [apt-mirror/apt-mirror#167]
Err:31 http://xxxxxxxxxxxxxxxxx/ubuntu focal-security/main amd64 c-n-f Metadata
  File has unexpected size (11096 != 11076). Mirror sync in progress? [IP: 10.7.77.213 80]
  Hashes of expected file:
   - Filesize:11076 [weak]
   - SHA256:e8f068ab8f8c497ff5abe433c377ebcfb2d0d76e251120db4c3164a965f59855
   - SHA1:517eaaa4b066c8b76b16cac3952f8efdef4aa5a9 [weak]
   - MD5Sum:faa8b40c710106da61a73489f8b69504 [weak]
  Release file created at: Thu, 22 Sep 2022 15:46:39 +0000
Get:40 http://xxxxxxxxxxxxxxxxx/ubuntu focal-security/universe amd64 c-n-f Metadata [15.1 kB]
Err:40 http://xxxxxxxxxxxxxxxxx/ubuntu focal-security/universe amd64 c-n-f Metadata

Fetched 337 kB in 4s (88.1 kB/s)
Reading package lists... Done
E: Failed to fetch http://xxxxxxxxxxxxxxxxx/ubuntu/dists/focal-updates/main/cnf/Commands-amd64.xz  File has unexpected size (15956 != 15952). Mirror sync in progress? [IP: 10.7.77.213 80]
   Hashes of expected file:
    - Filesize:15952 [weak]
    - SHA256:4690a94f3b299b448db149f58b40c6c1706590cb5c51a05766142dc3af6d57a8
    - SHA1:1e6e0b3271033a457354ab19917ce3cfd013b3fb [weak]
    - MD5Sum:d999641822ceaef6658106297830a99d [weak]
   Release file created at: Thu, 22 Sep 2022 15:16:05 +0000
E: Failed to fetch http://xxxxxxxxxxxxxxxxx/ubuntu/dists/focal-updates/universe/cnf/Commands-amd64.xz
E: Failed to fetch http://xxxxxxxxxxxxxxxxx/ubuntu/dists/focal-backports/universe/cnf/Commands-amd64.xz  Hash Sum mismatch
   Hashes of expected file:
    - Filesize:860 [weak]
    - SHA256:9a4adbb519ebf1ddfc09eb5f4b4e58c9dff11a1bf2a90c9d56776ab6444ac6ad
    - SHA1:8623521cc1e4bc4a9377d09a986e9b53da92fa00 [weak]
    - MD5Sum:9c969e814455c82e618d3f506bcaa911 [weak]
   Hashes of received file:
    - SHA256:e626747ab33b397368f940b2c5637606f6a16e2004ae9e8a3db7292ee43f4801
    - SHA1:d26f0532f45d6dea17ba83980cd6f2b7d991d307 [weak]
    - MD5Sum:cf625324c3b9506d50931452d3c9a14c [weak]
    - Filesize:860 [weak]
   Last modification reported: Wed, 28 Sep 2022 18:17:11 +0000
   Release file created at: Thu, 22 Sep 2022 16:07:21 +0000
E: Failed to fetch http://xxxxxxxxxxxxxxxxx/ubuntu/dists/focal-security/main/cnf/Commands-amd64.xz  File has unexpected size (11096 != 11076). Mirror sync in progress? [IP: 10.7.77.213 80]
   Hashes of expected file:
    - Filesize:11076 [weak]
    - SHA256:e8f068ab8f8c497ff5abe433c377ebcfb2d0d76e251120db4c3164a965f59855
    - SHA1:517eaaa4b066c8b76b16cac3952f8efdef4aa5a9 [weak]
    - MD5Sum:faa8b40c710106da61a73489f8b69504 [weak]
   Release file created at: Thu, 22 Sep 2022 15:46:39 +0000
E: Failed to fetch http://xxxxxxxxxxxxxxxxx/ubuntu/dists/focal-security/universe/cnf/Commands-amd64.xz
E: Some index files failed to download. They have been ignored, or old ones used instead.
root@detomcreativedev01:/etc/apt/sources.list.d# timed out waiting for input: auto-logout

**Comment by chutzimir** [comment]
There are a few open PRs that may help with this kind of issue. Think #156 should help with this kind of issue by downloading from the checksum locations.

**Comment by SupaHiro** [comment]
@chutzimir  yes I believe so too. Let me see if I can get that PR merged in this week.
