### ISSUE TITLE
Some packages are not downloaded

### ISSUE THREAD

**Issue by larissafoobar** [apt-mirror/apt-mirror#170]
Hi,

I am having a strange issue with apt-mirror

For my ubuntu 22.04 repo, some files are not downloaded when I run apt-mirror.
When I run "apt install mono-runtime-common" I'm greeted by:
`E: Failed to fetch http://<repo-url>/ubuntu/pool/universe/m/mono/mono-runtime-common_6.8.0.105%2bdfsg-3.2_amd64.deb (404)`

It does however exist on http://se.archive.ubuntu.com/ (the repo I'm mirroring). It seems to be files with "-3.2" in them that are missing and fail when I try to install them (not confirmed). I dont see anything obvious in apt mirror logs. I have noticed that some urls get cut off when apt mirror tries to download the associated files, like:

`http://se.archive.ubuntu.com/ubuntu/pool/main/s/ssl-cert/ssl-cert_ `which results in a 404, since there is no file by that name.

So, I suspect something in the apt mirror-code is cutting off URLs, causing it to fail its download of certain packages and thus some packages fail (404) when referred to using apt install. They are simply never downloaded to the repo. Haven't been able to figure out what is wrong. Would love some help!

**Comment by chutzimir** [comment]
The first filename you pasted has a `%2b` in it, and there is an open PR #143 to address that. I wonder if you have problems with any packages that have a + in their name.

Does installing `libcrypto++-doc` work for example? How about `vim-poke` (which should download `vim-poke_2.1+dfsg-2_all.deb` as of today?

**Comment by larissafoobar** [comment]
Thank you so much for responding! 

vim-poke installs just fine (2.1+dfsg-2). As does libcrypto++-doc.

mono-devel does not, for example, as "mono-runtime-common_6.8.0.105%2bdfsg-3.2_amd64.deb" among others fail. All the failed ones have "dfsg-3.2" in them. Packages that have "dfsg-2" do not fail. 

It seems apt-mirror fails to download some of those packages from the original mirror.

**Comment by larissafoobar** [comment]
Hi,

It seems the latest version works perfectly with ubuntu 22.04. For some reason I was running a version from this summer and hadn't noticed the updates.

Thank you so much for your help! I now see mono-runtime-common with 3.2 in the filename on the repo.

You may close this issue.
