### ISSUE TITLE
Failed to fetch http://x.x.x.x/ubuntu/mirror/archive.ubuntu.com/ubuntu/dists/jammy/main/cnf/Commands-amd64

### ISSUE THREAD

**Issue by jozb09** [apt-mirror/apt-mirror#176]
Hello Team,

Kindly, assist to resolve this issue. 
I configured a local repository running Ubuntu 22.04

On client when I run apt update I get

E: Failed to fetch http://x.x.x.x/ubuntu/mirror/archive.ubuntu.com/ubuntu/dists/jammy/main/cnf/Commands-amd64  404  Not Found [IP: x.x.x.x 80]
E: Failed to fetch http://x.x.x.x/ubuntu/mirror/archive.ubuntu.com/ubuntu/dists/jammy-updates/main/cnf/Commands-amd64  404  Not Found [IP: x.x.x.x 80]
E: Failed to fetch http://x.x.x.x/ubuntu/mirror/archive.ubuntu.com/ubuntu/dists/jammy-backports/main/cnf/Commands-amd64  404  Not Found [IP: x.x.x.x 80]
E: Failed to fetch http://x.x.x.x/ubuntu/mirror/archive.ubuntu.com/ubuntu/dists/jammy-security/main/cnf/Commands-amd64  404  Not Found [IP: x.x.x.x 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by chutzimir** [comment]
Can you try the latest version of apt-mirror from this repository and see if it fixes your problems?

You can just

```
wget https://raw.githubusercontent.com/apt-mirror/apt-mirror/master/apt-mirror
chmod +x ./apt-mirror
```

**Comment by jozb09** [comment]
Hello @chutzimir
Thanks for your reply. I did what you shared 
![image](https://github.com/apt-mirror/apt-mirror/assets/18210409/29e962c8-39bd-4fbd-9e3b-9f8d9ad571a9)


But when I run apt update on client I get 
E: Failed to fetch http://x.x.x.x/ubuntu/mirror/archive.ubuntu.com/ubuntu/dists/jammy-updates/universe/cnf/Commands-amd64  404  Not Found [IP: x.x.x.x 80]
E: Failed to fetch http://x.x.x.x/ubuntu/mirror/archive.ubuntu.com/ubuntu/dists/jammy-security/universe/cnf/Commands-amd64  404  Not Found [IP: x.x.x.x 80]
E: Failed to fetch http://x.x.x.x/ubuntu/mirror/archive.ubuntu.com/ubuntu/dists/jammy/universe/cnf/Commands-amd64  404  Not Found [IP: x.x.x.x 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by chutzimir** [comment]
Interestingly, the file is not available upstream anyway, so this may not be a problem with apt-mirror.

E.g., http://archive.ubuntu.com/ubuntu/dists/jammy-updates/universe/cnf/ does not have a file Commands-amd64

I would suggest looking at your webserver logs to see if there are any obvious errors (e.g., files not served due to wrong permissions on files), or try run apt update with some extra debugging:

```
apt -oDebug::pkgAcquire::Worker=1 update
```

**Comment by jozb09** [comment]
Hello @chutzimir 

I checked on the webserver log, var/log/apache2/error.log and nothing with permission issues. 
I tried also to run the command you shared but still the same error when I run the update command on the client. 

Do you have another means to sort it out? It's 3 weeks now am not able to sort this.

**Comment by jozb09** [comment]
This is my mirror.list file
![image](https://github.com/apt-mirror/apt-mirror/assets/18210409/ff027de6-583f-43e0-96a6-abb77199161e)

**Comment by chutzimir** [comment]
You are not mirroring **jammy-updates universe** and **jammy-security universe** and these are the URLs you are getting the error for. Try the following, restart your mirror, and you'll be fine:

```
deb http://archive.ubuntu.com/ubuntu jammy           main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu jammy-updates   main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu jammy-security  main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
```

**Comment by jozb09** [comment]
Am going to add those and update the mirror.

**Comment by jozb09** [comment]
Hello @chutzimir 

I still get this
<img width="948" alt="image" src="https://github.com/apt-mirror/apt-mirror/assets/18210409/aabcb79e-987a-469d-bcb9-6875db846812">

**Comment by jozb09** [comment]
Hello @chutzimir 

IU still get this 
![image](https://github.com/apt-mirror/apt-mirror/assets/18210409/2121bdd1-2f6e-4320-91eb-49442776c850)

**Comment by chutzimir** [comment]
I can guarantee that I have verified I can make a working mirror using the configuration I pasted above, so I would suggest
1. double-check your configuration file
2. check the apt-mirror output for any errors
3. on the client - do `apt clean` followed by `apt update`

**Comment by jozb09** [comment]
I do thank you for the response. 

I decided to attach the mirror.list file here, Kindly check on it and advise if I have something which is not correct. 
[mirror.list.txt](https://github.com/apt-mirror/apt-mirror/files/11660703/mirror.list.txt)

**Comment by jozb09** [comment]
check the apt-mirror output for any errors****

How can I check for the apt-mirror output? share the log file location

**Comment by chutzimir** [comment]
> check the apt-mirror output for any errors****
> 
> How can I check for the apt-mirror output? share the log file location 

It doesn't have a log file. The output goes to stdout and stderr.

**Comment by jozb09** [comment]
my config file is okay? did you find anything which trigger issues?

**Comment by chutzimir** [comment]
No, it looks good. My only other advice is to take the latest version of the script from this repository, and run it manually, and check the output...

**Comment by jozb09** [comment]
@chutzimir 
You meant from this link?
https://raw.githubusercontent.com/apt-mirror/apt-mirror/master/apt-mirror

**Comment by vrabha** [comment]
@jozb09
Even I faced the same issue. Seems like an issue with apt-mirror from that repository.

Try to clone this repo: https://github.com/Stifler6996/apt-mirror.git and use apt-mirror from it. It fixed my issue and I'm sure this is going to fix it for you as well.

**Comment by jozb09** [comment]
Hello @vrabha 

I run the bellow commands

git clone https://github.com/Stifler6996/apt-mirror.git
 sudo cp /usr/bin/apt-mirror /usr/bin/apt-mirror.original
 
cp -r apt-mirror /usr/bin/apt-mirror
sudo chown root:root /usr/bin/apt-mirror && sudo chmod 755 /usr/bin/apt-mirror
sudo apt-mirror

Then I run apt-get clean on client
And then I run apt-get update
But still I get error
![image](https://github.com/apt-mirror/apt-mirror/assets/18210409/1ceceb7b-93c0-4aec-9270-1a517b6db84c)

**Comment by chutzimir** [comment]
@jozb09 I now noticed the mirror.list file you attached...

> I decided to attach the mirror.list file here, Kindly check on it and advise if I have something which is not correct. [mirror.list.txt](https://github.com/apt-mirror/apt-mirror/files/11660703/mirror.list.txt)

Can you remove the first four lines

```
deb http://archive.ubuntu.com/ubuntu jammy main restricted
deb http://archive.ubuntu.com/ubuntu jammy-updates main restricted
deb http://archive.ubuntu.com/ubuntu jammy-security main restricted
deb http://archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
```

and only leave the 4 lines below

```
deb http://archive.ubuntu.com/ubuntu jammy           main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu jammy-updates   main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu jammy-security  main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
```

I don't know how apt-mirror behaves when you define the same distro multiple times.

> @chutzimir You meant from this link? https://raw.githubusercontent.com/apt-mirror/apt-mirror/master/apt-mirror

Did you try this version or not?

**Comment by chutzimir** [comment]
Ah, @jozb09 ... I didn't realize this time you're reporting that the files are missing for `focal`. Same problem, you're not mirroring the `universe` for the `focal` distros in your config.

**Comment by jozb09** [comment]
Hello @chutzimir 

So, are you suggesting for my /etc/apt/mirror.list have only four lines below?

deb http://archive.ubuntu.com/ubuntu jammy           main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu jammy-updates   main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu jammy-security  main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse

Kindly, check for my sources.list for my client
![image](https://github.com/apt-mirror/apt-mirror/assets/18210409/0a1900cf-6ca0-444f-a840-ac63a4331060)

**Comment by jozb09** [comment]
Hello @chutzimir

So, are you suggesting for my /etc/apt/mirror.list have only four lines below?

deb http://archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu jammy-security main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse

Kindly, check for my sources.list for my client
![image](https://github.com/apt-mirror/apt-mirror/assets/18210409/35d12797-5143-4083-916b-23405fec3bdc)

**Comment by chutzimir** [comment]
If your client is using `focal`, then you need to mirror focal.

The first message in this report, your client was using `jammy`.

If you have clients on both, you need to mirror both. E.g.:

```
deb http://archive.ubuntu.com/ubuntu focal           main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu focal-updates   main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu focal-security  main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse

deb http://archive.ubuntu.com/ubuntu jammy           main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu jammy-updates   main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu jammy-security  main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
```

**Comment by jozb09** [comment]
I think we are progressing.

Now I get this
![image](https://github.com/apt-mirror/apt-mirror/assets/18210409/1854a5d5-8578-4a99-ad99-dcae56a05597)

I tried to run apt clean but still same issue as from screenshot

**Comment by jozb09** [comment]
Oooh, I managed to sort it out. I tried to run the apt-mirror again

This has been a hustle, but I thank you for your help. you're really my rock.

**Comment by chutzimir** [comment]
> Oooh, I managed to sort it out. I tried to run the apt-mirror again
> 
> This has been a hustle, but I thank you for your help. you're really my rock.

You're welcome. Please close the issue if you are satisfied.

**Comment by jozb09** [comment]
This has been closed.
