### ISSUE TITLE
sanitise_url is not correctly picking up specified ports

### ISSUE THREAD

**Issue by RobWC** [apt-mirror/apt-mirror#19]
The regex is incorrect:

Change:     $uri =~ s&:\d+/&/&;    # and port information
To:     $uri =~ s&:\d+/$&/&;    # and port information

**Comment by thib-ack** [comment]
Thanks for the patch, this fix the issue for me :+1: 
With a 
> deb http://W.X.Y.Z:9480/apt/debian jessie main

entry in my mirror.list, I had issues like this in apt-mirror :

> Failed to open Release file from /var/spool/apt-mirror/skel/W.X.Y.Z/apt/debian/dists/jessie/Release at /usr/bin/apt-mirror line 486, < STREAM > line 9451.

But with the patch, it works fine. The port is taken into account.

**Comment by nshalman** [comment]
This works for me too. 

@jwater7 please consider opening a pull request.

Maintainers, please either merge a pull request, or just cherry pick and apply https://github.com/jwater7/apt-mirror/commit/6677bd4b6ab26541f75bc1dc92a78f8f5fc64c6f

**Comment by jwater7** [comment]
A pull request was attempted already but I’m not sure rejecting it was the right thing to do.  https://github.com/apt-mirror/apt-mirror/pull/20
