### ISSUE TITLE
apt-mirror requires gzip compressed index files

### ISSUE THREAD

**Issue by cody-somerville** [apt-mirror/apt-mirror#30]
apt-mirror will attempt to download both gzip and bzip2 compressed indexes but is hard coded to only attempt to parse indexes compressed with gzip. As a result, apt-mirror will fail to mirror a repository that does not publish gzip compressed indexes.

apt-mirror should attempt to download gzip, bzip2, lzma, and uncompressed indexes and be able to successfully mirror a repository if any one format is provided.

**Comment by RomanVolak** [comment]
Same problem on debian-multimedia only uncompressed index.
