### ISSUE TITLE
Cannot handle 'deb [arch=amd64] http://...' format

### ISSUE THREAD

**Issue by twang2218** [apt-mirror/apt-mirror#32]
When I try to create a mirror of [cloudera-cdh5](https://www.cloudera.com/content/cloudera-content/cloudera-docs/CDH5/latest/CDH5-Installation-Guide/cdh5ig_cdh5_install.html?scroll=topic_4_4_1_unique_1__section_dfx_p51_nj_unique_1), I found this error.

The apt list file is under `/etc/apt/sources.list.d/cloudera-cdh5.list` on my system, and the content is :

```
deb [arch=amd64] http://archive.cloudera.com/cdh5/ubuntu/precise/amd64/cdh precise-cdh5 contrib
deb-src http://archive.cloudera.com/cdh5/ubuntu/precise/amd64/cdh precise-cdh5 contrib
```

I try to do the mirror by following command and got errors:

``` bash
vagrant@ubuntu:~$ sudo apt-mirror /etc/apt/sources.list.d/cloudera-cdh5.list 
Downloading 15 index files using 15 threads...
Begin time: Mon Apr 14 17:04:35 2014
[15]... [14]... [13]... [12]... [11]... [10]... [9]... [8]... [7]... [6]... [5]... [4]... [3]... [2]... [1]... [0]... 
End time: Mon Apr 14 17:04:36 2014

Proceed indexes: [SPsh: 1: cannot open [arch=amd64]//dists/http://archive.cloudera.com/cdh5/ubuntu/precise/amd64/cdh/precise-cdh5/binary-amd64/Packages.gz: No such file
apt-mirror: can't open index in proceed_index_gz at /usr/bin/apt-mirror line 460.
vagrant@ubuntu:~$ 
```

If I have to change the apt .list to the form below to make it work:

```
deb-amd64 http://archive.cloudera.com/cdh5/ubuntu/precise/amd64/cdh precise-cdh5 contrib
deb-src http://archive.cloudera.com/cdh5/ubuntu/precise/amd64/cdh precise-cdh5 contrib
```
- OS: Ubuntu 12.04
- apt-mirror: 0.4.8-5

Could you add support of `[arch=amd64]`-like format? Thanks.

**Comment by twang2218** [comment]
I created a PR for this issue, please have a look. Thanks.

**Comment by bdrung** [comment]
Thanks. I merged your PR.
