### ISSUE TITLE
debian 8 error

### ISSUE THREAD

**Issue by canghaiwuhen1** [apt-mirror/apt-mirror#44]
Fetched 437 kB in 1s (289 kB/s)  
W: Failed to fetch http://10.18.25.30/debian/dists/jessie-updates/main/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://10.18.25.30/debian/dists/jessie-updates/main/binary-i386/Packages  Hash Sum mismatch

   Failed to fetch http://10.18.25.30/debian/dists/jessie-backports/main/source/Sources  Hash Sum mismatch

W: Failed to fetch http://10.18.25.30/debian/dists/jessie-backports/non-free/source/Sources  Hash Sum mismatch

W: Failed to fetch http://10.18.25.30/debian/dists/jessie-backports/contrib/source/Sources  Hash Sum mismatch

W: Failed to fetch http://10.18.25.30/debian/dists/jessie-backports/main/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://10.18.25.30/debian/dists/jessie-backports/non-free/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://10.18.25.30/debian/dists/jessie-backports/contrib/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://10.18.25.30/debian/dists/jessie-backports/main/binary-i386/Packages  Hash Sum mismatch

W: Failed to fetch http://10.18.25.30/debian/dists/jessie-backports/non-free/binary-i386/Packages  Hash Sum mismatch

W: Failed to fetch http://10.18.25.30/debian/dists/jessie-backports/contrib/binary-i386/Packages  Hash Sum mismatch

W: Failed to fetch http://10.18.25.30/debian/dists/jessie-proposed-updates/main/source/Sources  Hash Sum mismatch

W: Failed to fetch http://10.18.25.30/debian/dists/jessie-proposed-updates/non-free/source/Sources  Hash Sum mismatch

W: Failed to fetch http://10.18.25.30/debian/dists/jessie-proposed-updates/main/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://10.18.25.30/debian/dists/jessie-proposed-updates/non-free/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://10.18.25.30/debian/dists/jessie-proposed-updates/main/binary-i386/Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.

And I delete the file will be ok!

rm -rf debian/dists/jessie-updates/main/binary-amd64/Packages.bz2
rm -rf debian/dists/jessie-updates/main/binary-i386/Packages.bz2
rm -rf debian/dists/jessie-backports/main/source/Sources.bz2
rm -rf debian/dists/jessie-backports/non-free/source/Sources.bz2
rm -rf debian/dists/jessie-backports/contrib/source/Sources.bz2
rm -rf debian/dists/jessie-backports/main/binary-amd64/Packages.bz2
rm -rf debian/dists/jessie-backports/non-free/binary-amd64/Packages.bz2
rm -rf debian/dists/jessie-backports/contrib/binary-amd64/Packages.bz2
rm -rf debian/dists/jessie-backports/main/binary-i386/Packages.bz2
rm -rf debian/dists/jessie-backports/non-free/binary-i386/Packages.bz2
rm -rf debian/dists/jessie-backports/contrib/binary-i386/Packages.bz2
rm -rf debian/dists/jessie-proposed-updates/main/source/Sources.bz2
rm -rf debian/dists/jessie-proposed-updates/non-free/source/Sources.bz2
rm -rf debian/dists/jessie-proposed-updates/main/binary-amd64/Packages.bz2
rm -rf debian/dists/jessie-proposed-updates/non-free/binary-amd64/Packages.bz2
rm -rf debian/dists/jessie-proposed-updates/main/binary-i386/Packages.bz2
rm -rf debian/dists/jessie-updates/main/binary-amd64/Packages
rm -rf debian/dists/jessie-updates/main/binary-i386/Packages
rm -rf debian/dists/jessie-backports/main/source/Sources
rm -rf debian/dists/jessie-backports/non-free/source/Sources
rm -rf debian/dists/jessie-backports/contrib/source/Sources
rm -rf debian/dists/jessie-backports/main/binary-amd64/Packages
rm -rf debian/dists/jessie-backports/non-free/binary-amd64/Packages
rm -rf debian/dists/jessie-backports/contrib/binary-amd64/Packages
rm -rf debian/dists/jessie-backports/main/binary-i386/Packages
rm -rf debian/dists/jessie-backports/non-free/binary-i386/Packages
rm -rf debian/dists/jessie-backports/contrib/binary-i386/Packages
rm -rf debian/dists/jessie-proposed-updates/main/source/Sources
rm -rf debian/dists/jessie-proposed-updates/non-free/source/Sources
rm -rf debian/dists/jessie-proposed-updates/main/binary-amd64/Packages
rm -rf debian/dists/jessie-proposed-updates/non-free/binary-amd64/Packages
rm -rf debian/dists/jessie-proposed-updates/main/binary-i386/Packages

**Comment by chutzimir** [comment]
This was fixed with #156. Can be closed.

**Comment by SupaHiro** [comment]
Marking this issue as resolved. Thanks @chutzimir!
