### ISSUE TITLE
Checksums of downloaded files

### ISSUE THREAD

**Issue by jimmypw** [apt-mirror/apt-mirror#49]
Firstly I know that apt checks the signature before installing, that isn't the point of this issue - read on.

Apt-mirror tool doesn't seem to check the checksum of the downloaded file vs the checksum of the file as is reported in the Release file. Nor does it check the checksum of the previously downloaded file on disk vs the file on the remote server to ensure the local version isn't corrupt.

I believe this is necessary in order to ensure that you have mirrored a valid repository and that failures will not occour later when you attempt to install the packages. Also in case of local filesystem corruption you are able to repair the repository without needing to download everything again.

It is evident that this was intended at one point but does not appear to be fully implemented.

**Comment by diosney** [comment]
+1 `debmirror` supports this option and its very handy for paranoic people like me.

I think this should be a boolean option (default: disabled) since could add lot of time to complete.

**Comment by jimmypw** [comment]
Absolutely disabled by default to prevent current implementations from being suddenly bogged down.

Given the inactivity of this project i'm happy to give it a go implementing, i'll need to read the code some more to understand exactly what's going on.

What options will we want?

checksum_enabled = 1|0 (Default: 0)
checksum_hash = md5 | sha1 | sha256 (Default: md5)
checksum_fail_action = notify | delete | retry (Default: notify) - retry retries up to a maximum of once before notifying

**Comment by bhavin192** [comment]
Seriously this feature is needed, right now I'm facing problems due to half downloaded files and I don't want to download everything again 
Do you have any simple script to do hash check and remove those files ?

**Comment by highdn** [comment]
apt-mirror outputs an "$var_path/MD5" file with all the MD5 sums.
You should be able to validate your local repo against this file via:
$ md5sum -c .../path/to/apt-mirror/var/MD5

See https://linux.die.net/man/1/md5sum

And yes, expect it to be slow for any reasonable sized repo.

**Comment by Yvan-Masson** [comment]
@bhavin192 I just encountered some package checksum errors using my newly created mirror, and I searched for a similar tool: I found and tried https://github.com/phenobarbital/check_debian_repository which does the job pretty well (but have a look on the bug report I made there).

**Comment by bdrung** [comment]
I plan to rewrite apt-mirror in Python and then verify the checksums (but I can't say when I find time to do it).

**Comment by proxyconcept** [comment]
> Can I tel md5sum to make $base_path top directory?

You just have to move to your $base_path before running md5sum : 
`$ cd /data/apt-mirror/mirror`
`$ md5sum -c /data/apt-mirror/var/MD5`

But apt-mirror seems to have several problems and the project abandoned... As mentioned in the [debian wiki](https://www.debian.org/mirror/ftpmirror) we will consider replacing apt-mirror with [debmirror](https://salsa.debian.org/debian/debmirror)

**Comment by bodaay** [comment]
Suggested Script to solve:
https://github.com/apt-mirror/apt-mirror/issues/113

**Comment by sir-xw** [comment]
> I plan to rewrite apt-mirror in Python and then verify the checksums (but I can't say when I find time to do it).

Hello, inspired by you, I wrote a python version of Apt-mirror. The checksum check feature will be integrated later. (https://github.com/sir-xw/apt-mirror-python)
