### ISSUE TITLE
not download DEP-11 from source

### ISSUE THREAD

**Issue by dynaguy1** [apt-mirror/apt-mirror#57]
I just build new mirror for Ubuntu 16.04 Xenial and apt-mirror won't download the dep11 directory at all.

The source has:
http://ca.archive.ubuntu.com/ubuntu/dists/xenial/main/dep11/

My local mirror after update it shows "404 not found"

**Comment by monotek** [comment]
There is already a fix available:
https://github.com/apt-mirror/apt-mirror/pull/56

Its already implemented in 16.04 so you also could just extract /usr/bin/apt-mirror from the xenial package: http://packages.ubuntu.com/xenial/all/apt-mirror/download

**Comment by bdrung** [comment]
Merge proposal #56 merged. It will be part of the next release (0.5.2)
