### ISSUE TITLE
Warnings on repositories without MD5sums

### ISSUE THREAD

**Issue by yaunj** [apt-mirror/apt-mirror#66]
I'm using apt-mirror on Ubuntu 16.04, and some of the repositories I'm mirroring does not contain MD5sums in the Packages files. This results in warnings like this:

`Global symbol "$package" requires explicit package name (did you forget to declare "my $package"?) at /usr/bin/apt-mirror line 787`

Line 787 in Ubuntu 16.04 corresponds to [line 798](https://github.com/apt-mirror/apt-mirror/blob/0.5.2/apt-mirror#L798) in version 0.5.2.

> `print FILES_MD5 $lines{"MD5sum:"} . "  " . remove_double_slashes( $path . "/" . $lines{"Filename:"} ) . "\n";`

Appending `if defined $lines{"MD5sum:"}` to the line silences the error. However, you probably shouldn't silence all these possibly missing checksums. Maybe you could add some logic to warn if there isn't at least one checksum in the file?

**Comment by genokan** [comment]
Would seeing messages like this:

Use of uninitialized value $lines{"MD5sum:"} in concatenation (.) or string at /usr/bin/apt-mirror line 787

Be related to your issue? Did you see any of the above when troubleshooting? 

Thanks

**Comment by yaunj** [comment]
That seems like it could be related, yes. Don't recall seeing that warning, and I don't have logs handy at the moment, but I guess it could depend on the version of apt-mirror or Perl?

In my case, the repository I was mirroring had SHA sums, so I appended the if check above to line 787 and hope for a fix before next update.

**Comment by Raboo** [comment]
If anybody need a apt repo without MD5 to test.
`deb-amd64 https://packages.chef.io/stable-apt xenial  main`

**Comment by vveider** [comment]
@bdrung,

I still see these messages for Ubuntu 18.04 at least.
Should I file new bug or we can reopen this one?

```
Use of uninitialized value $lines{"MD5sum:"} in concatenation (.) or string at /usr/bin/apt-mirror line 787, <STREAM> line 6.
```

**Comment by Raboo** [comment]
The README says "New maintainer(s) wanted". So unless you are willing to become the maintainer, your issue is not going to be solved.

**Comment by vveider** [comment]
Oh, I see. Thanks.
