### ISSUE TITLE
Use of uninitialized value $config{"options"}

### ISSUE THREAD

**Issue by gerbert** [apt-mirror/apt-mirror#68]
Multiple warnings about uninitialized value $config{"options"}

[apt-mirror_err.txt](https://github.com/apt-mirror/apt-mirror/files/724758/apt-mirror_err.txt)
[perl_ver.txt](https://github.com/apt-mirror/apt-mirror/files/724757/perl_ver.txt)

**Comment by draconis244** [comment]
same here

**Comment by nikmoon** [comment]
a similar problem with the latest version

**Comment by gnif** [comment]
Seeing this on the latest version also:

`Use of uninitialized value $config{"options"} in pattern match (m//) at /usr/local/bin/apt-mirror line 300, <CONFIG> line 3.`

**Comment by Kunzol** [comment]
I suggest do change the line 297:

`$config{'options'} = $+{options};`
to
`$config{'options'} = $+{options}?$+{options}?"";`

Should I make a pull request for this ?

**Comment by ed1023** [comment]
Hey Kunzol
I tried your edit on line 297 

> $config{'options'} = $+{options};
> to
> $config{'options'} = $+{options}?$+{options}?"";

when I try to run apt-mirror I get a 
  syntax error at /usr/bin/apt-mirror line 297, near """;"

**Comment by jlskywalker** [comment]
I'm _pretty_ sure he intended:

`$config{'options'} = $+{options}?$+{options}:"";`

Obviously I'm not 100% sure but I can't imagine another reason to use the ? operator in this context.

**Comment by Zitrax** [comment]
What (if any) are the effects of this bug other than the warning messages in the console?
