### ISSUE TITLE
Components-$arch.yml.xz files not picked up by apt-mirror

### ISSUE THREAD

**Issue by duk3luk3** [apt-mirror/apt-mirror#69]
Hi,

these files are listed in the `Release` files but ignored by apt-mirror. I parse the `Release` files and do a md5sum-check on the files listed there, leading to this error:

> md5sum: main/dep11/Components-amd64.yml.xz: No such file or directory

Here is one example in the ubuntu repos: http://de.archive.ubuntu.com/ubuntu/dists/devel/main/dep11/Components-amd64.yml.xz

**Comment by Kunzol** [comment]
You only need one of the files in your repository. The developper decided to download only the ".gz" files. 

Reasons could be: 
1. less files to download (save time and bandwith)
2. icons- files are only available with ".gz", which makes the regex easier. 

See line 669 in the code. 
If you really need to download all, simply change the reges in this line. 
...`tar)\.gz$} )` 
to 
...`tar)\.(gz|xz)$} )`

I have not tested this, use on your own risk.
