### ISSUE TITLE
Support For SSL based repo's with keys

### ISSUE THREAD

**Issue by freibuis** [apt-mirror/apt-mirror#75]
Would it be possible to support repos that use SSL keys to authenticate

nginx repo comes to mind.

**Comment by bdrung** [comment]
apt-mirror uses wget. So specifying https:// to use SSL should work or do you want to use a client certificate?

**Comment by josephharding** [comment]
I needed this as well, ended up just dropping in these lines around line 247 to add additional arguments to the `wget` call:

```
    if ( length( get_variable("certificate") ) ) { push( @args, "--certificate=" . get_variable("certificate") ); }
    if ( length( get_variable("ca-certificate") ) ) { push( @args, "--ca-certificate=" . get_variable("ca-certificate") ); }
    if ( length( get_variable("private-key") ) ) { push( @args, "--private-key=" . get_variable("private-key") ); }
```

Then I include these config fields with the value being paths to my various credential files.
