### ISSUE TITLE
Configurable apt-mirror base directory.

### ISSUE THREAD

**Issue by wayneworkman** [apt-mirror/apt-mirror#76]
Hello, I need to be able to define what the apt-mirror base directory is via an argument.

Currently, it's hard-coded to `/var/spool/apt-mirror` but I need to use different directories instead to ease technical complications caused by the hard-coded path.

Thanks,
Wayne

**Comment by Kunzol** [comment]
You can configure it in the config file. Usually /etc/apt/mirror.list or the file you give as commandlineargument.
The base directory is **not** hardcoded.

**Comment by bdrung** [comment]
Yes, you can set in mirror.list:
```
set base_path    /path/to/mirror
```

**Comment by wayneworkman** [comment]
@bdrung Thank you for that.
