### ISSUE TITLE
how to set defaultarch  in mirror.list for both i386 and amd64

### ISSUE THREAD

**Issue by missuor** [apt-mirror/apt-mirror#81]
I can not find any doc or examples to tell how to configurate the defaultarch in mirror.list
I want to mirror both i386 and amd64
I just do the follow steps 
`set defaultarch i386` and run sudo apt-mirror
`set defaultarch amd64` and run sudo apt-mirror
:(

**Comment by Kunzol** [comment]
You need to configure the "deb-lines" accordingly: 

```
deb-amd64 http://....
deb-i386 http://....
```

**Comment by missuor** [comment]
I use the following lines to solve it.
```
dev@bbt:~$ cat /etc/apt/mirror.list|grep -v ^# |grep -v ^$
set base_path   /home/dev/mirrors/apt-mirror 
set nthreads     20
set _tilde 0
deb [arch=i386] http://ubuntu-cloud.archive.canonical.com/ubuntu xenial-updates/ocata main
deb [arch=amd64] http://ubuntu-cloud.archive.canonical.com/ubuntu xenial-updates/ocata main
deb-src http://ubuntu-cloud.archive.canonical.com/ubuntu xenial-updates/ocata main
clean http://ubuntu-cloud.archive.canonical.com/ubuntu
```
But I still wander if there are any choices to solve it via `set defaultarch` :)
thx all the same.

**Comment by evandrix** [comment]
is `deb [arch=i386]` equivalent to `deb-i386`?

**Comment by akurach** [comment]
> is `deb [arch=i386]` equivalent to `deb-i386`?

just use this

```
sed -Ei 's@^deb (.*)@deb-i386  \1\ndeb-amd64 \1@' /etc/apt/mirror.list
```
