### ISSUE TITLE
Does apt-mirror incrementally synchronize?

### ISSUE THREAD

**Issue by streambinder** [apt-mirror/apt-mirror#89]
Hi. I'm using this tool to replicate main ubuntu repositories.
I have a question: once replicated, if I run another synchronization:
1. does it fetch only the missing data? If a full synchronization weighed ~150Gb, the latter would weigh less?
2. would it keep my already synchronized packages, even if deleted from the main repository

Thank you.

**Comment by box293** [comment]
Yes, it only syncs the newer files. If you look at this pull request I created I added a "dry_run" option. https://github.com/apt-mirror/apt-mirror/pull/86. This will tell you how much will be downloaded but will not actually do the download.

> would it keep my already synchronized packages, even if deleted from the main repository

Nothing gets deleted until you run the `clean.sh` script. You can look at this script to see what is going to be deleted.

**Comment by streambinder** [comment]
Thank you. :)
